### ISSUE TITLE
Kafka Admin security schemes allow only service accounts and not token 

### ISSUE THREAD

**Issue by wtrocki** [bf2fc6cc711aee1a0c2a/kafka-admin-api#227]
We have that 

 ```
  securitySchemes:
    Bearer:
      type: oauth2
      description: Access token used with OAuth 2.0
      flows:
        clientCredentials:
          tokenUrl: /token
          scopes: {}
   ```
   
   In openapi file:
   https://github.com/bf2fc6cc711aee1a0c2a/kafka-admin-api/blob/96c5e76b8867a763eb542a25fd74c08b6267f26a/kafka-admin/src/main/resources/META-INF/openapi.yaml#L407-L414
   
   
   That would render service account authentication:
   

but we should also supply token based authentication which is also supported and in most cases more desired:

```
  securitySchemes:
    Bearer:
      scheme: bearer
      bearerFormat: JWT
      type: http
```

**Comment by wtrocki** [comment]
Ping @MikeEdgar WDYT?

**Comment by MikeEdgar** [comment]
I agree - any issue with renaming the existing `Bearer` to `OAuth2`? This will need to be dynamically added (in the OASFilter) only when OAuth2 is enabled.

**Comment by wtrocki** [comment]
To make sure that I understand do you mind putting full snippet of what will be pushed to the repository? As for dynamically added - that is no problem - we only use version in the repository right now for both SDK and API portal

**Comment by MikeEdgar** [comment]
@wtrocki - it would end up like this:
```yaml
security:
- OAuth2: []
- Bearer: []
.
.
.
  securitySchemes:
   OAuth2: 
     type: oauth2 
     description: Access token used with OAuth 2.0 
     flows: 
       clientCredentials: 
         tokenUrl: "/token" 
         scopes: {} 
    Bearer:
      scheme: bearer
      bearerFormat: JWT
      type: http
```
